### ISSUE TITLE
Full Allure support

### ISSUE THREAD

**Issue by noomorph** [wix-incubator/jest-allure2-reporter#4]
## 🧪 Beta release

- [x] #13 (2.0.0-alpha.5)
- [x] #14 (2.0.0-alpha.6)
- [x] Implement plugin subsystem (#15) (2.0.0-alpha.7)
- [x] Pretty-printing and syntax highlighting for the test code (#15) (2.0.0-alpha.7) 
- [x] Differentiate between `broken` and `failed` tests (#15) (2.0.0-alpha.7)
- [x] Introduce default test categories (#16) (2.0.0-alpha.8)
- [x] Implement test file exec error customizer (#17) (2.0.0-alpha.10)
- [x] Implement JSDoc metadata provider (#15) (2.0.0-alpha.9) 🚧 
- [x] Implement executor plugin based on `ci-info` (#18) (2.0.0-alpha.11)
- [x] Finalize how the reporter [will be plugged](https://github.com/wix-incubator/jest-environment-emit) into existing projects
- [x] Pre-release 🏆 (2.0.0-beta.1)

## 🎉  Official release

- [x] Fix CJS and ESM exports (#22)
- [x] Implement `injectGlobals` flag (#22)
- [x] Fix: docblock parsing for `@tag` and `@link` (#24)
- [x] Custom file handlers (#24)
- Fix: issue with attachment appearing twice (#24) (needs an extra confirmation)
- [x] Integrate internally in Detox OSS (https://github.com/wix-incubator/detox-allure2-adapter/pull/1)
  - pack directories
  - filter iOS and Android logs
- [x] Switch to Handlebars (#29)
- [x] Performance: distribute `onRunComplete` report generation between `onRunStart` and `onTestFileResult`
- [x] Create a comprehensive E2E test suite
- [x] Integrate internally via DWP
- [x] Generate demo reports and documentation from the E2E suite
- [ ] Bugfixing and documentation feedback
- [ ] Fix broken suite links on the home page
- [ ] Finish documentation website: API page, revisit the guides
- [ ] Release 🥳

**Comment by noomorph** [comment]
The work is happening in https://github.com/wix-incubator/jest-extend-report repo meanwhile. It will be used then as a dependency to extend jest reports with metadata available only from Circus environment.

**Comment by noomorph** [comment]
Heads up for the people following the issue – the work is ongoing and already halfway.  👷‍♂️

**Comment by noomorph** [comment]
Update: there's a beta release of [jest-metadata](https://github.com/wix-incubator/jest-metadata) already, so hopefully soon I'll be able to integrate with it.

**Comment by Gorodb** [comment]
@noomorph but why are you waiting for jest-metadata? Everything is already implemented in the allure-js-commons module. The request was mostly about getting access to all allure metadata how it was implemented here https://github.com/zaqqaz/jest-allure
Because without it allure reporter looks useless.

**Comment by noomorph** [comment]
@Gorodb I have a certain technical vision around this project, and nothing among existing alternatives can satisfy my needs. I am aware of your fork, yet I view the decision to use those "commons" as a dead end. That approach with the environment augmentation and JSDoc pragma parsing they use is too opinionated and one-sided.

`jest-metadata` will definitely see the public release within the next two months or sooner. I have big plans on it even beyond the context of this particular project.

**Comment by noomorph** [comment]
The work is in progress. 🏃  Since I work on this project only one day in a week, it might take 2-3 weeks to finish it, but I have a cautious optimism that the feature will land in mid- or end-June.

The new version will be most likely 2.x, and I'll start dogfooding in a few projects I work with.

**Comment by noomorph** [comment]
The alpha release is [ready for trying out](https://www.npmjs.com/package/jest-allure2-reporter/v/2.0.0-alpha.2) (under `2.0.0-alpha.2`).

It lacks JSDoc annotation support and, overall, might be moderately buggy (especially around the dynamic `allure.*` API), but courageous users can try it. 

I've started dogfooding the release here in Detox: https://github.com/wix/Detox/pull/4211 

Please note that the website might be "hallucinating" about certain features and APIs (some are yet to be implemented, and some are because I wrote docs before implementing). Consult with the roadmap at the top of this issue page to see where we're at).

Website: https://wix-incubator.github.io/jest-allure2-reporter/

**Comment by noomorph** [comment]
I guess this issue stays open for too long, whereas the state of the project is a solid beta+.

The docs still need some love, but I'll create that as a separate issue now.
On the tags and branches side, we exited `beta`.
